export default () =>
     [ {"flg_registro_dinap_digep":"G",
        "dsc_tipo_condicao_dependente":"SEM EXIGENCIA DE CONDICAO",
        "dsc_tipo_dependencia":"IR, E, S",
        "cod_pessoa_dependente":37958,
        "dat_nascimento_dependente":"2015-10-24",
        "nom_dependente":"JOAO FELIPE DE OLIVEIRA PINHO",
        "num_cpf_dependente":"07492036175",
        "nom_mae_pessoa":"HERTHA SANTOS DE OLIVEIRA",
        "nom_pai_pessoa":"ISMAEL DE FREITAS PINHO",
        "cod_sexo":1,"num_idade_dependente":"1",
        "cod_pessoa_titular":9659},
        {"flg_registro_dinap_digep":"G",
        "dsc_tipo_condicao_dependente":"NAO INFORMADO",
        "dsc_tipo_dependencia":"IR, E, S",
        "cod_pessoa_dependente":9660,
        "dat_nascimento_dependente":"1980-12-10",
        "nom_dependente":"HERTHA SANTOS DE OLIVEIRA",
        "num_cpf_dependente":"72009497104",
        "nom_mae_pessoa":"DAMIANA MARIA DE OLIVEIRA SANTOS",
        "nom_pai_pessoa":"ISMAEL DE FREITAS PINHO",
        "cod_sexo":2,"num_idade_dependente":"36",
        "cod_pessoa_titular":9659}
    ];